apiVersion: v1
kind: Pod
metadata:
  name: sanity-test
  labels:
    App: sanity-test
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: sock-volume
    - mountPath: /usr/bin/docker
      name: docker-bin
  volumes:
  - name: sock-volume
    hostPath:
      # directory location on host
      path: /var/run/docker.sock
  - name: docker-bin
    hostPath:
      path: /usr/bin/docker  
      # this field is optional
      type: Directory
